CREATE TABLE SPORTSDATAENTITY (
	EVENT_ID 			VARCHAR2(100) NOT NULL, 
	EVENT_DATE 			DATE NOT NULL, 
	DOCUMENT 			CLOB NOT NULL, 
	MESSAGE_ID 			VARCHAR2(150), 
	MESSAGE_TIMESTAMP 	TIMESTAMP, 
	DECORATED_TIMESTAMP TIMESTAMP, 
	UPDATED_TIMESTAMP 	TIMESTAMP, 
	REPLACES 			NUMBER(10,0), 
	UPDATES 			NUMBER(10,0), 
	EXPIRY 				DATE,
	
	PRIMARY KEY ( EVENT_DATE, EVENT_ID )
)
